# Generated by Django 3.1.7 on 2021-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='requires_exercise',
            field=models.BooleanField(),
        ),
    ]
