# Generated by Django 3.1.7 on 2021-04-09 05:30

import buddi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile_image_placeholder.png', upload_to=buddi.models.UserProfile.profile_image_upload),
        ),
    ]
