# Generated by Django 3.1.7 on 2021-04-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0002_auto_20210406_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_subregion_of',
            field=models.ForeignKey(default='UK', on_delete=django.db.models.deletion.CASCADE, to='buddi.region'),
        ),
    ]
