# Generated by Django 3.1.7 on 2021-04-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0003_region_is_subregion_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='is_subregion_of',
        ),
    ]
