# Generated by Django 3.1.7 on 2021-04-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0003_userprofile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='No message', max_length=400),
        ),
        migrations.AddField(
            model_name='comments',
            name='made_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buddi.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
