# Generated by Django 3.1.7 on 2021-04-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0004_remove_region_is_subregion_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_parent_region',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='is_subregion_of',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='buddi.region'),
        ),
    ]
