# Generated by Django 3.1.7 on 2021-04-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0006_auto_20210407_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='is_subregion_of',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buddi.region'),
        ),
    ]
