# Generated by Django 3.1.7 on 2021-04-06 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='contend',
            field=models.FileField(upload_to='blog/contend'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='blog/image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contend',
            field=models.FileField(upload_to='blog/contend'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='blog/image'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='contend',
            field=models.FileField(upload_to='blog/contend'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='image',
            field=models.ImageField(upload_to='blog/image'),
        ),
    ]
