# Generated by Django 3.1.7 on 2021-04-07 22:57

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20210407_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=120, null=True)),
                ('category', models.CharField(max_length=120)),
                ('hero_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/blog/articles/'), upload_to=blog.models.Article.upload)),
                ('author', models.CharField(max_length=120)),
                ('date_published', models.DateTimeField()),
                ('date_edited', models.DateTimeField(null=True)),
                ('content', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/blog/articles/'), upload_to=blog.models.Article.upload)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shop',
            name='topic',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vet',
            name='topic',
            field=models.CharField(max_length=120),
        ),
    ]
