# Generated by Django 3.1.7 on 2021-04-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210408_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_edited',
            new_name='date_last_edited',
        ),
    ]
